version: '3.9'

volumes:
  postgres-volume:
    
services:
  api:
    image: pierogies-api
    build:
      context: ./PierogiesSystem
      dockerfile: src/WebUI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure
    links:
      - "db:pierogiesDb-production"
    networks:
      - app-network
  
  db:
    container_name: pierogies-db
    image: postgres
    command: postgres -c 'max_connections=100'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network
      
      
  client:
    image: pierogies-client
    build:
      context: ./PierogiesFrontend
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge